POST {{replicatorUrl}}/write
Content-Type: text/plain

let creator: Jinaga.User = {
  publicKey: "--- FAKE PUBLIC KEY ---"
}

let site: Blog.Site = {
  creator,
  domain: "michaelperry.net"
}

let post: Blog.Post = {
    createdAt: "2022-08-16T15:23:13.231Z",
    site
}

let title: Blog.Post.Title = {
    post,
    value: "Introducing Jinaga Replicator",
    prior: []
}
let title2: Blog.Post.Title = {
    post,
    value: "Introduction to the Jinaga Replicator",
    prior: [ title ]
}