POST {{replicatorUrl}}/save
Content-Type: application/json

{
    "facts": [{
        "type": "Test.Root",
        "hash": "sdkjbks",
        "predecessors": {},
        "fields": {
            "identifier": "rootfact"
        }
    }]
}