services:
  jinaga-test:
    image: jinaga-test
  db:
    image: jinaga-postgres-fact-keystore
    environment:
    - POSTGRES_PASSWORD=superuser
    - APP_USERNAME=dev
    - APP_PASSWORD=devpw
    - APP_DATABASE=integrationtest
    ports:
    - "5432:5432"